export const PUBLIC_SPOTIFY_REDIRECT_URI = process.env.NEXT_SPOTIFY_REDIRECT_URI
export const SPOTIFY_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID
export const SPOTIFY_SECRET = process.env.SPOTIFY_SECRET
